algoritmo "FazSomaProcedimento"

var
X,Y,N1,N2 : Inteiro

Procedimento Soma(A, B :Inteiro)
Inicio
   Escreval("Recebi o valor ",A)
   Escreval("Recebi o valor ",B)
   Escreval("A soma entre os dois e", A + B,".")
FimProcedimento

inicio
      Escreva("Digite um número: ")
      Leia (N1)
      Escreva("Digite outro número: ")
      Leia(N2)
      X <- N1
      Y <- N2
      Soma(x,y)
fimalgoritmo
