algoritmo "Creuza01"
// Função :
// Autor :
// Data : 02/04/2022
// Seção de Declarações 
var
Ano1, Ano2, Resultado: Real
Nome: Caractere

inicio
      Escreval("Qual o seu nome?")
      Leia(Nome)
      Escreval ("Em qual ano nós estamos ",nome,"?")
      Leia(Ano1)
      Escreval ("Em qual ano você nasceu?")
      Leia(Ano2)
      Resultado <- (Ano1-Ano2)
      Escreva(Nome,",", " a sua idade é de",Resultado," anos.")
// Seção de Comandos 
fimalgoritmo
