algoritmo "SomaParâmetrosReferência"
// Função :
// Autor :
// Data : 03/05/2022
// Seção de Declarações 
var
   X,Y : Inteiro
Procedimento Soma (var A,B: Inteiro)
Inicio
      A <- A + 1
      B <- B + 2
      Escreval("Valor de A = ", A)
      Escreval("Valor de B = ", B)
      Escreval("Soma A + B = ", A+B)
FimProcedimento
inicio
// Seção de Comandos
   X <- 4
   Y <- 8
   Soma (X, Y)
   Escreval("Valor de x = ", X)
   Escreval("Valor de Y = ", Y)
fimalgoritmo
